
POST http://127.0.0.1:9135 HTTP/1.1
Content-Type: application/json
Content-Length: 54
Authorization: Basic QUE6QkI=
Connection: close

{
    "method": "getblockcount",
    "params": "[]",
    "jsonrpc": "2.0"
}
